name        = "ideano-blunix"
license     = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Professional business theme for consulting and services"
homepage    = "https://github.com/ideano/ideano-blunix"
demosite    = ""
tags        = ["business", "consulting", "multilingual", "responsive", "clean", "rtl", "farsi", "arabic"]
features    = ["responsive", "multilingual", "seo", "tailwind", "rtl"]
min_version = "0.156.0"

[author]
  name = "Ideano Corp modified from original theme from Blunix GmbH"
  homepage = "https://www.ideano.com"
