[en]
label = "English"
locale = "en-us"
direction = "ltr"
contentDir = "content/en"
title = "Hugo Theme Starter"
weight = 1

[en.params]
# Independent visual theme selections.
# Colors: default, aquamarine, ...
# Fonts: default, iran-sans-x, work-sans, elegant
theme-colors = "default"
theme-fonts = "default"

footer_copyright = "Copyright {year} Your Company.\n\nAll rights reserved."
footer_social_media = "Follow Us"
footer_listed_with = "Affiliations"
footer_listed_with_text = "Proud member of"
flag_image = "english"
flag_alt = "English"
label = "English"

[en.params.site]
keywords = "linux, debian, ubuntu, consulting, hosting, training, classes, courses"
author = "Ideano corp"
website = "https://www.ideano.com"
email = "info@ideano.com"
version = "2.0.0"
title = "Ideano Corp Tehran: Embedded systesm design, Consulting and TV Monitoring solutions"
description = "Embedded systesm design, Consulting and TV Monitoring solutions, Project based Linux Embedded Design as well as Embedded Linux Design Workshops and Trainings"
background_404 = "/images/404/background.webp"

[en.params.logo]
dark = "images/navbar/logo-dark-en.svg"
light = "images/navbar/logo-light-en.svg"

[[en.params.social_media]]
name = "Twitter"
url = "https://twitter.com/"
title = "Follow us on Twitter"
icon = "bi bi-twitter"

[[en.params.social_media]]
name = "LinkedIn"
url = "https://www.linkedin.com/"
title = "Connect on LinkedIn"
icon = "bi bi-linkedin"

[[en.params.social_media]]
name = "GitHub"
url = "https://github.com/"
title = "View our GitHub"
icon = "bi bi-github"

[[en.params.social_media]]
name = "Instagram"
url = "https://instagram.com/"
title = "Follow on Instagram"
icon = "bi bi-instagram"

[[en.params.affiliation_links]]
name = "Hugo Themes"
url = "https://themes.gohugo.io/"
title = "Hugo Themes Directory"

[[en.params.affiliation_links]]
name = "Hugo"
url = "https://gohugo.io/"
title = "Hugo Main Site"
