[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
identifier = "services"
name = "Services"
pageRef = "#"
weight = 20

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 40

[[main]]
name = "Contact"
pageRef = "/#contact"
weight = 80

[[footer]]
identifier = "footer_first_column"
name = "Company"
pageRef = "#"
weight = 10

[[footer]]
parent = "footer_first_column"
name = "Home"
pageRef = "/"
weight = 10

[[footer]]
parent = "footer_first_column"
name = "Services"
pageRef = "/consulting/"
weight = 20

[[footer]]
parent = "footer_first_column"
name = "Jobs"
pageRef = "/jobs/"
weight = 60

[[footer]]
parent = "footer_first_column"
name = "Legal & Privacy"
pageRef = "/legal-and-privacy/"
weight = 70

[[footer]]
parent = "footer_first_column"
name = "Contact"
pageRef = "/#contact"
weight = 80

[[footer]]
identifier = "footer_2nd_column"
name = "Resources"
pageRef = "#"
weight = 20

[[footer]]
parent = "footer_2nd_column"
name = "Blog"
pageRef = "/blog/"
weight = 10

[[footer]]
identifier = "footer_3rd_column"
name = "External"
pageRef = "#"
weight = 30

[[footer]]
parent = "footer_3rd_column"
name = "google"
url = "https://google.com/"
weight = 10

[[services]]
name = "Consulting"
pageRef = "/consulting/"
weight = 10
[services.params]
icon = "bi bi-graph-up"

[[services]]
name = "Development"
pageRef = "/#development"
weight = 20
[services.params]
icon = "bi bi-display"

[[services]]
name = "Training"
pageRef = "/#training"
weight = 30
[services.params]
icon = "bi bi-mortarboard"
