[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
identifier = "services"
name = "Services"
pageRef = "#"
weight = 20

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 40

[[main]]
name = "Contact"
pageRef = "/#contact"
weight = 80

[[footer]]
identifier = "website"
name = "Company"
pageRef = "#"
weight = 10

[[footer]]
parent = "website"
name = "Home"
pageRef = "/"
weight = 10

[[footer]]
parent = "website"
name = "Services"
pageRef = "/consulting/"
weight = 20

[[footer]]
parent = "website"
name = "Contact"
pageRef = "/#contact"
weight = 30

[[footer]]
identifier = "hosting"
name = "Resources"
pageRef = "#"
weight = 20

[[footer]]
parent = "hosting"
name = "Blog"
pageRef = "/blog/"
weight = 10

[[services]]
name = "Consulting"
pageRef = "/consulting/"
weight = 10
[services.params]
icon = "uil uil-chart-line"

[[services]]
name = "Development"
pageRef = "/#development"
weight = 20
[services.params]
icon = "uil uil-desktop"

[[services]]
name = "Training"
pageRef = "/#training"
weight = 30
[services.params]
icon = "uil uil-graduation-cap"
