featured_image = 'featured.webp'

[[contact]]
name = "contact@example.com"
icon = "bi bi-envelope"
link = "mailto:contact@example.com"

[[contact]]
name = "+1 234 567 890"
icon = "bi bi-telephone"
link = "tel:+1234567890"

[[banner_link]]
name = "+1 234 567 890"
icon = "bi bi-phone"
link = "tel:+1234567890"

[[banner_link]]
name = "contact@example.com"
icon = "bi bi-envelope"
link = "mailto:contact@example.com"
