# enable this if you want to modify theme, and make it possible to change predefined styles. Remember to install nodejs and then, npm install first
compileTailwind = false
featured_image = 'featured.webp'

[[contact]]
name = "contact@example.com"
icon = "bi bi-envelope"
link = "mailto:contact@example.com"

[[contact]]
name = "+1 234 567 890"
icon = "bi bi-telephone"
link = "tel:+1234567890"

[[banner_link]]
name = "+1 234 567 890"
icon = "bi bi-phone"
link = "tel:+1234567890"

[[banner_link]]
name = "contact@example.com"
icon = "bi bi-envelope"
link = "mailto:contact@example.com"

[services.google_analytics]
id = ""

[services.microsoft_clarity]
id = ""

[services.cloudflare_web_analytics]
token = ""

[services.plausible]
domain = ""
url = ""

[services.matomo]
id = ""
url = ""

[services.umami]
id = ""
url = ""

[services.open_web_analytics]
id = ""
url = ""